ALTER TABLE `Banner`
  ADD COLUMN `height` INTEGER NULL,
  ADD COLUMN `imagePosition` INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN `imageRotation` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `accentColor` VARCHAR(7) NULL;
