"use client";
import { useEffect, useState, useRef } from "react";
import Link from "next/link";
import { apiFetch, ApiError } from "@/lib/api";
import { uploadImage } from "@/lib/cloudinary";
import { useAdminAuth } from "@/lib/AdminAuthContext";
type Product = { id: string; name: string; status: string; basePrice: string; images: { url: string }[] };
type Detail = { id: string; name: string; slug: string; description: string | null; imageUrl: string | null; active: boolean; products: Product[] };
const panel = "rounded-xl border border-ink/15 bg-surface p-5 shadow-sm";
const button = "rounded-lg border border-ink/20 bg-surface px-3 py-2 text-sm disabled:opacity-40";
export default function CollectionEditor({ params }: { params: { id: string } }) {
 const { token } = useAdminAuth();
 const dialogRef=useRef<HTMLDialogElement>(null);
 const [detail,setDetail]=useState<Detail|null>(null);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);const [uploading,setUploading]=useState(false);
 const [picker,setPicker]=useState(false);const [query,setQuery]=useState("");const [page,setPage]=useState(1);const [items,setItems]=useState<Product[]>([]);const [total,setTotal]=useState(0);const [loading,setLoading]=useState(false);const [filter,setFilter]=useState("");const [view,setView]=useState("grid");
 useEffect(()=>{if(!token)return;let ignore=false;apiFetch<Detail>(`/admin/collections/${params.id}`,{token}).then(data=>{if(!ignore)setDetail(data);}).catch(()=>{if(!ignore)setError("Could not load collection.");});return()=>{ignore=true;};},[token,params.id]);
 useEffect(()=>{if(!picker||!token)return;let ignore=false;setLoading(true);const timer=setTimeout(()=>{apiFetch<{items:Product[];total:number}>(`/admin/collection-products?q=${encodeURIComponent(query)}&page=${page}`,{token}).then(data=>{if(!ignore){setItems(data.items);setTotal(data.total);}}).catch(()=>{if(!ignore){setItems([]);setError("Could not load products.");}}).finally(()=>{if(!ignore)setLoading(false);});},250);return()=>{ignore=true;clearTimeout(timer);};},[picker,query,page,token]);
 useEffect(()=>{if(picker)dialogRef.current?.showModal();},[picker]);
 async function save(){if(!detail||!token)return;setBusy(true);setError("");setNotice("");try{const saved=await apiFetch<Detail>(`/admin/collections/${detail.id}`,{method:"PATCH",token,body:JSON.stringify({name:detail.name,description:detail.description||null,active:detail.active,productIds:detail.products.map(p=>p.id),...(detail.imageUrl?.startsWith('/')?{}:{imageUrl:detail.imageUrl})})});setDetail({...detail,slug:saved.slug});setNotice("Collection saved.");}catch(e){setError(e instanceof ApiError?e.message:"Could not save collection.");}finally{setBusy(false);}}
 if(!detail)return <div role="status">{error||"Loading collection..."}</div>;
 const shown=detail.products.filter(p=>p.name.toLowerCase().includes(filter.toLowerCase()));
 return <div className="mx-auto max-w-6xl">
  <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Link href="/admin/collections" aria-label="Back to collections">←</Link><h1 className="text-2xl">{detail.name}</h1></div><div className="flex gap-2"><Link className={button} href={`/collections/${detail.slug}`} target="_blank">View ↗</Link><button onClick={save} disabled={busy||uploading||detail.name.trim().length<2} className="rounded-lg bg-ink px-5 py-2 text-sm text-paper disabled:opacity-40">{busy?"Saving...":"Save changes"}</button></div></div>
  {error&&<p role="alert" className="mb-4 text-red-600">{error}</p>}{notice&&<p role="status" className="mb-4 text-green-700 dark:text-green-400">{notice}</p>}
  <fieldset disabled={busy} className="grid gap-5 lg:grid-cols-[minmax(0,2fr)_minmax(260px,1fr)]">
   <section className={`${panel} flex flex-col gap-6 sm:flex-row`}><div className="w-full shrink-0 sm:w-44"><label className="flex aspect-square cursor-pointer flex-col items-center justify-center overflow-hidden rounded-xl border border-dashed border-ink/40 text-sm">{detail.imageUrl?<img src={detail.imageUrl} alt="Collection cover" className="h-full w-full object-cover"/>:<span>↑ Upload image</span>}<input aria-label="Upload collection image" type="file" accept="image/*" className="sr-only" disabled={uploading} onChange={async e=>{const file=e.target.files?.[0];if(!file||!token)return;setUploading(true);setError("");try{const imageUrl=await uploadImage(file,token);setDetail(d=>d?{...d,imageUrl}:d);}catch{setError("Image upload failed. Check Cloudinary settings.");}finally{setUploading(false);}}}/></label>{uploading?<p className="mt-2 text-xs">Uploading...</p>:detail.imageUrl&&<button className="mt-2 text-xs underline" onClick={()=>setDetail({...detail,imageUrl:null})}>Remove image</button>}</div><div className="flex-1 space-y-4"><label className="block text-xs text-ink-soft">Collection name<input maxLength={80} required className="mt-1 w-full rounded border border-ink/15 bg-transparent p-2 text-xl font-semibold text-ink" value={detail.name} onChange={e=>setDetail({...detail,name:e.target.value})}/></label><label className="block text-xs text-ink-soft">Description<textarea maxLength={300} rows={4} placeholder="Add a description" className="mt-1 w-full rounded border border-ink/15 bg-transparent p-2 text-sm text-ink" value={detail.description||""} onChange={e=>setDetail({...detail,description:e.target.value})}/></label><p className="text-xs text-ink-soft">{detail.active?"Published on online store":"Hidden from online store"}</p></div></section>
   <aside className="space-y-5"><section className={panel}><h2 className="mb-4 font-semibold">Products</h2><p className="mb-4 text-sm text-ink-soft">Choose the products that belong in this collection.</p><button className={button} onClick={()=>{setPicker(true);setQuery("");setPage(1);}}>＋ Add products</button><p className="mt-4 text-xs text-ink-soft">Remove individual items below. Changes apply when you save.</p></section><section className={panel}><h2 className="mb-3 font-semibold">Publishing</h2><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={detail.active} onChange={e=>setDetail({...detail,active:e.target.checked})}/>Visible on online store</label></section></aside>
   <section className={`${panel} lg:col-span-2`}><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Collection items <span className="ml-2 rounded-full bg-ink/5 px-2 py-1 text-sm">{detail.products.length}</span></h2><div className="flex gap-2"><button className={button} aria-pressed={view==='grid'} onClick={()=>setView('grid')}>Grid</button><button className={button} aria-pressed={view==='list'} onClick={()=>setView('list')}>List</button></div></div><input aria-label="Search collection items" placeholder="Search collection items" className="rang-input mb-5 max-w-md" value={filter} onChange={e=>setFilter(e.target.value)}/>{!shown.length?<div className="rounded-xl border border-dashed border-ink/20 p-12 text-center text-sm text-ink-soft">{detail.products.length?"No products match your search.":"Your collection is empty. Add products to get started."}</div>:<div className={view==='grid'?"grid grid-cols-2 gap-4 md:grid-cols-4":"space-y-3"}>{shown.map(p=><article key={p.id} className={`overflow-hidden rounded-xl border border-ink/15 ${view==='list'?'flex items-center gap-4 p-3':''}`}><div className={view==='grid'?'aspect-square bg-ink/5':'h-16 w-16 shrink-0 bg-ink/5'}>{p.images[0]?<img src={p.images[0].url} alt={p.name} className="h-full w-full object-cover"/>:<span className="flex h-full items-center justify-center text-xs">No image</span>}</div><div className="flex-1 p-3"><p className="text-sm font-medium">{p.name}</p><p className="mt-1 text-xs text-ink-soft">PKR {Number(p.basePrice).toLocaleString()} · {p.status}</p><button className="mt-3 text-xs underline" onClick={()=>setDetail({...detail,products:detail.products.filter(item=>item.id!==p.id)})}>Remove</button></div></article>)}</div>}</section>
  </fieldset>
  {picker&&<dialog ref={dialogRef} onCancel={()=>setPicker(false)} aria-label="Add products" onKeyDown={e=>{if(e.key==='Escape')setPicker(false);}} className="fixed inset-0 z-50 max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-xl bg-transparent p-4 backdrop:bg-black/50"><div className="mx-auto my-8 max-w-2xl rounded-xl bg-surface p-6 text-ink"><div className="mb-4 flex justify-between"><h2 className="text-xl">Add products</h2><button onClick={()=>setPicker(false)} className={button}>Done</button></div><input autoFocus className="rang-input mb-4" placeholder="Search all products, including drafts" aria-label="Search products" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/>{loading?<p>Loading products...</p>:items.length?items.map(p=><label key={p.id} className="flex cursor-pointer items-center gap-3 border-b border-ink/10 py-3"><input type="checkbox" checked={detail.products.some(item=>item.id===p.id)} onChange={e=>setDetail({...detail,products:e.target.checked?[...detail.products,p]:detail.products.filter(item=>item.id!==p.id)})}/>{p.images[0]&&<img src={p.images[0].url} alt="" className="h-12 w-12 rounded object-cover"/>}<span className="text-sm">{p.name}<small className="block text-ink-soft">{p.status} · PKR {Number(p.basePrice).toLocaleString()}</small></span></label>):<p>No products found.</p>}<div className="mt-5 flex justify-between"><button disabled={page===1||loading} className={button} onClick={()=>setPage(page-1)}>Previous</button><span className="text-sm">Page {page}</span><button disabled={page*24>=total||loading} className={button} onClick={()=>setPage(page+1)}>Next</button></div></div></dialog>}
 </div>;
}
